#!/bin/sh

# ZRAM Setup
lsmod | grep -q zram || insmod  /usr/lib/zram.ko
echo 64M > /sys/block/zram0/disksize
mkswap /dev/zram0
grep -q '/dev/zram0' /proc/swaps || swapon /dev/zram0

# Swapfile
grep -q '/root/swapfile' /proc/swaps || swapon /root/swapfile

# USB Mass Storage
/usr/local/bin/init_mass.sh


