#!/bin/sh

# ==========================================================
# ==      A Robust Service Script for FbTerm              ==
# ==========================================================

# This script is designed to be called by the init system
# during the boot sequence (runlevels).

case "$1" in
  start)
    echo "Starting Framebuffer Terminal (FbTerm)..."
    
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    stty iutf8 -F /dev/console
    # stty iutf8 -F /dev/pts/1

    # A short delay to ensure the system is fully ready
    sleep 1
    
    # Release the framebuffer from the default kernel console
    if [ -e /sys/class/vtconsole/vtcon1/bind ]; then
        echo 0 > /sys/class/vtconsole/vtcon1/bind
    fi
    
    # Launch fbterm in a new session, detached from init,
    # with its I/O explicitly redirected to the physical console.
    setsid sh -c 'exec fbterm </dev/tty1 >/dev/tty1 2>&1' &
    # sleep 0.2
    # /bin/sh -c "/usr/bin/yaft" > /dev/console &
    ;;
  stop)
    echo "Stopping Framebuffer Terminal (FbTerm)..."
    killall fbterm
    if [ -e /sys/class/vtconsole/vtcon1/bind ]; then
        echo 1 > /sys/class/vtconsole/vtcon1/bind
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
